In [1]:
import random
import numpy as np

In [2]:
# Define the system of linear equations: Ax = b
A = np.array([[3, 2], [1, -1]])  # Coefficient matrix
b = np.array([12, 1])            # Right-hand side vector

In [3]:
A, b

(array([[ 3,  2],
        [ 1, -1]]),
 array([12,  1]))

In [4]:
# Parameters
population_size = 50
num_generations = 200
mutation_rate = 0.1
elitism_count = 2  # Number of best individuals to carry over to the next generation
variable_range = (-10, 10)  # Range for initial values of x

In [5]:
# Fitness function
def fitness(individual):
    x = np.array(individual)
    error = np.sum((np.dot(A, x) - b) ** 2)  # Sum of squared errors
    return error

In [6]:
fitness(np.array([2,3]))

np.int64(4)

In [7]:
# Initialize population
def create_individual():
    return [random.uniform(variable_range[0], variable_range[1]) for _ in range(len(b))]

In [8]:
create_individual()

[-5.0956396040418195, -2.7492979677946616]

In [9]:
fitness(create_individual())

np.float64(37.95454298606618)

In [10]:
population = [create_individual() for _ in range(population_size)]

In [11]:
population

[[-6.800760425886536, -7.801290604992626],
 [-6.325399568898429, -9.796744449919244],
 [-8.499298507778416, -7.695957913299831],
 [-0.36650279589451173, -6.809807428577567],
 [8.958684006243828, 7.795228899698177],
 [5.985007367098444, 1.3928921689882685],
 [8.538452591988609, -3.125831714551042],
 [-3.1917052026995503, -7.864280447818315],
 [-2.656169156843074, -1.9780595737124997],
 [-2.8651742908951423, -4.791704843924041],
 [-0.5638769354008808, -5.282853049253225],
 [-8.351813310098448, -1.457810857729033],
 [3.337682037600999, -1.0265923385344973],
 [4.468031706169985, 5.777790388903849],
 [7.094305074070245, -8.623800951772221],
 [1.828718304250355, -1.9689778727661178],
 [-9.611346594785907, 7.6583588427306175],
 [-6.218314572948842, -4.756685609536227],
 [-0.41399043666481994, 2.09547373746231],
 [-2.387235107657178, 7.057327408441374],
 [-8.366899956825659, -6.095390752296989],
 [-1.7331661350714338, 5.039577612738311],
 [4.133688407931116, -5.068362592939799],
 [9.1400579506

In [12]:
# Genetic operators
def crossover(parent1, parent2):
    # Blend crossover (alpha determines the blending factor)
    alpha = random.random()
    child = [alpha * parent1[i] + (1 - alpha) * parent2[i] for i in range(len(parent1))]
    return child

In [13]:
p1 = np.array([1,2])
p2 = np.array([3,4])

In [14]:
crossover(p1, p2)

[np.float64(1.1646887027463835), np.float64(2.1646887027463837)]

In [15]:
def mutate(individual):
    for i in range(len(individual)):
        if random.random() < 0.9: 
            individual[i] += random.gauss(0, 0.5)  # Gaussian mutation
    return individual
mutate(p1)

array([0, 1])

In [16]:
def mutate(individual):
    # Adaptive mutation: mutation rate decreases over generations
    adaptive_mutation_rate = mutation_rate * (1 - (generation / num_generations))
    for i in range(len(individual)):
        if random.random() < adaptive_mutation_rate:
            individual[i] += random.gauss(0, 0.5)  # Gaussian mutation
    return individual

In [17]:
# Main GA loop
for generation in range(num_generations):
    # Evaluate fitness
    fitness_scores = [fitness(individual) for individual in population]

    # Select parents using tournament selection
    def tournament_selection():
        tournament_size = 3
        tournament = random.sample(range(population_size), tournament_size)
        winner = min(tournament, key=lambda x: fitness_scores[x])
        return population[winner]

    # Create next generation
    new_population = []

    # Elitism: Carry over the best individuals
    elite_indices = np.argsort(fitness_scores)[:elitism_count]
    for i in elite_indices:
        new_population.append(population[i])
         # Fill the rest of the population with crossover and mutation
    
    while len(new_population) < population_size:
        parent1 = tournament_selection()
        parent2 = tournament_selection()
        child = crossover(parent1, parent2)
        child = mutate(child)
        new_population.append(child)

    population = new_population

    # Print best individual in this generation
    best_individual = min(population, key=fitness)
    best_fitness = fitness(best_individual)
    print(f"Generation {generation + 1}: Best solution = {best_individual}, Fitness = {best_fitness}")

Generation 1: Best solution = [2.8346965876691366, 2.2437894686085977], Fitness = 1.1507637962405042
Generation 2: Best solution = [2.9479177338257037, 1.507632236576368], Fitness = 0.21372733515487058
Generation 3: Best solution = [2.8431565825054395, 1.736759151131773], Fitness = 0.011329341844401
Generation 4: Best solution = [2.8431565825054395, 1.736759151131773], Fitness = 0.011329341844401
Generation 5: Best solution = [2.8431565825054395, 1.736759151131773], Fitness = 0.011329341844401
Generation 6: Best solution = [2.825335627711212, 1.8060906830040113], Fitness = 0.008147535183454527
Generation 7: Best solution = [2.8048239529650356, 1.7820165430728325], Fitness = 0.0009822153336912
Generation 8: Best solution = [2.7968739295135574, 1.7911222026519733], Fitness = 0.0007693257983680942
Generation 9: Best solution = [2.80413096594609, 1.7857390010997414], Fitness = 0.0005984122365015013
Generation 10: Best solution = [2.8063407168837142, 1.7931093131560651], Fitness = 0.0002025

In [18]:
# Final result
best_individual = min(population, key=fitness)
best_fitness = fitness(best_individual)
print("\nFinal Best Solution:")
print(f"x = {best_individual}")
print(f"Fitness (sum of squared errors) = {best_fitness}")


Final Best Solution:
x = [2.8041801904073225, 1.7958204747416056]
Fitness (sum of squared errors) = 8.736996141946206e-05
